modity

diff --git a/wvga/mzdpi-wvga-autoinstall b/wvga/mzdpi-wvga-autoinstall
--- a/wvga/mzdpi-wvga-autoinstall
+++ b/wvga/mzdpi-wvga-autoinstall
@@ -2,22 +2,47 @@
 
 do_txt_dtb() {
 # now create dts file
-cat <<\EOF > /boot/mzp361wv1t.txt && 
- [gpio26=1]
- gpio=0-9=a2
- gpio=12-17=a2
- gpio=20-25=a2
- gpio=18,19=op,dh,pd
- display_rotate=3
- framebuffer_width=800
- framebuffer_height=480
- enable_dpi_lcd=1
- display_default_lcd=1
- dpi_group=2
- dpi_mode=87
- dpi_output_format=0x07f006
- hdmi_timings=480 0 41 20 60 800 0 5 10 10 0 0 0 60 0 32000000 3
-EOF&
+cat <<EOF > /boot/mzp361wv1t.txt
+[gpio26=1]
+gpio=0-9=a2
+gpio=12-17=a2
+gpio=20-25=a2
+gpio=18,19=op,dh,pd
+display_rotate=3
+framebuffer_width=800
+framebuffer_height=480
+enable_dpi_lcd=1
+display_default_lcd=1
+dpi_group=2
+dpi_mode=87
+dpi_output_format=0x07f006
+hdmi_timings=480 0 41 20 60 800 0 5 10 10 0 0 0 60 0 32000000 3
+EOF
+cat <<EOF > /etc/rc.local
+#!/bin/sh -e
+#
+# rc.local
+#
+# This script is executed at the end of each multiuser runlevel.
+# Make sure that the script will "exit 0" on success or any other
+# value on error.
+#
+# In order to enable or disable this script just change the execution
+# bits.
+#
+# By default this script does nothing.
+
+# Print the IP address
+_IP=$(hostname -I) || true
+if [ "$_IP" ]; then
+  printf "My IP address is %s\n" "$_IP"
+fi
+
+sudo python /home/pi/MZDPI/mzp361wv1t/led-pwm.py &
+sudo python /home/pi/MZDPI/mzp361wv1t/fan-pwm.py &
+
+exit 0
+EOF
 }
 
 
